TARGET=tester
CFLAGS=-g -std=c++14 -I ./Include -pipe -O3 -march=native

all: Objects $(TARGET)

clean:
	rm -rf $(TARGET) libUtilities.a Objects/*.[ao]


$(TARGET): Source/test.cpp libUtilities.a
	g++ $(CFLAGS) -o $@ $< -L ./ -lUtilities

libUtilities.a: Objects/Entity.o
	ar rcs $@ $^

Objects:
	mkdir -p Objects

Objects/%.o: Source/%.cpp
	g++ $(CFLAGS) -c -o $@ $<

Objects/Entity.o: Source/Entity.cpp Include/Entity.hpp
